spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SPRING_MAIL_HOST}
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: false
    protocol: smtp

application:
  security:
    jwt:
      security-key: ksjdfakjdalsnlaknslakncljfdalhfljslkvjnslkdmssdjhsohfowfjwpijrfpij
      expiration: 8640000
  mailing:
    frontend:
      activation-url: ${MAILING_ACTIVATION_URL}
  cors:
    origins: http://localhost:4200,http://localhost:8080
  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088

frontend:
  url: ${FRONTEND_URL}